imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: services.yml }
  - { resource: config_build.yml, ignore_errors: true }

doctrine:
  dbal:
    charset: utf8mb4
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_unicode_ci
    dbname: "%database_name%"
    driver: "%database_driver%"
    host: "%database_host%"
    password: "%database_password%"
    port: "%database_port%"
    types:
      ipaddress: SuplaBundle\Model\Doctrine\IpAddressType
      stringdatetime: SuplaBundle\Model\Doctrine\StringDateTime
      utcdatetime: SuplaBundle\Model\Doctrine\UTCDateTimeType
    user: "%database_user%"
    server_version: 5.5
    schema_filter: ~^(?!esp_)~
  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    auto_mapping: true

doctrine_migrations:
  namespace: Supla\Migrations

fos_oauth_server:
  access_token_class: SuplaBundle\Entity\OAuth\AccessToken
  auth_code_class: SuplaBundle\Entity\OAuth\AuthCode
  client_class: SuplaBundle\Entity\OAuth\ApiClient
  refresh_token_class: SuplaBundle\Entity\OAuth\RefreshToken
  db_driver: orm
  service:
    options:
      access_token_lifetime: 300
      refresh_token_lifetime: 500
    storage: SuplaBundle\Auth\SuplaOAuthStorage

fos_rest:
  routing_loader:
    default_format: json
  serializer:
    groups: ['basic']
  versioning: true
  view:
    view_response_listener: 'force'

framework:
  assets:
    packages:
      webpack:
        version_strategy: SuplaBundle\Twig\WebpackAssetVersionStrategy
  cache:
    app: cache.adapter.filesystem
    pools:
      api_rate_limit:
        adapter: cache.app
  csrf_protection: ~
  default_locale: "%locale%"
  form: ~
  fragments: ~
  http_method_override: true
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  secret: "%secret%"
  serializer:
    enable_annotations: true
    enabled: true
    name_converter: SuplaBundle\Serialization\NoopNameConverter
    circular_reference_handler: SuplaBundle\Serialization\ObjectIdCircularReferenceHandler
  session:
    cookie_lifetime: 0
    handler_id: ~
  templating:
    engines:
      - twig
  translator:
    fallbacks: en
  trusted_hosts: ~
  validation:
    enable_annotations: true

monolog:
  channels: [supla_api_rate_limit, supla_autodiscover, supla_direct_links, supla_server]
  handlers:
    main:
      channels: ['!supla_direct_links', '!supla_server', '!supla_api_rate_limit']
      action_level: error
      handler: main_logger
      type: fingers_crossed
    main_logger:
      level: info
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      type: rotating_file
      max_files: 14
    api_rate_limit:
      channels: [supla_api_rate_limit]
      level: warning
      path: "%kernel.logs_dir%/api_rate_limit.log"
      type: rotating_file
      max_files: 14
    autodiscover:
      channels: [supla_autodiscover]
      level: notice
      path: "%kernel.logs_dir%/autodiscover.log"
      type: rotating_file
      max_files: 14
    direct_links:
      channels: [supla_direct_links]
      level: notice
      path: "%kernel.logs_dir%/direct-links.log"
      type: rotating_file
      max_files: 14
    supla_server:
      channels: [supla_server]
      level: warning
      path: "%kernel.logs_dir%/supla-server.log"
      type: rotating_file
      max_files: 14

nelmio_cors:
  paths:
    '^/api/':
      origin_regex: true
      allow_origin: '%cors_allow_origin_regex%'
      allow_headers: ['*']
      allow_methods: ['POST', 'PUT', 'PATCH', 'HEAD', 'GET', 'DELETE']
      expose_headers: ['X-Total-Count', 'X-Count', 'X-Min-Timestamp', 'X-Max-Timestamp']
      max_age: 3600

parameters:
  act_as_broker_cloud: false
  fos_oauth_server.security.authentication.provider.class: SuplaBundle\Auth\SuplaOAuthProvider
  supla_protocol: https
  supla_server_socket: /var/run/supla/supla-server-ctrl.sock
  supla_url: '%supla_protocol%://%supla_server%'
  use_webpack_dev_server: false
  container.autowiring.strict_mode: true

sensio_framework_extra:
  request: { converters: true }

supla:
  accounts_registration_enabled: true
  autodiscover_url: https://autodiscover.supla.org
  api_rate_limit:
    enabled: false
    blocking: false
    user_default_limit: 9000/360
    global_limit: 320/60
  brute_force_auth_prevention:
    enabled: '%brute_force_auth_prevention_enabled%'
    max_failed_attempts: 3
    block_time_seconds: 1200
  clients_registration:
    registration_active_time:
      initial: 604800 # 1 week
      manual: 86400 # 24 hours
  io_devices_registration:
    registration_active_time:
      initial: 604800 # 1 week
      manual: 86400 # 24 hours
  maintenance:
    delete_non_confirmed_users_older_than_hours: 24
    delete_audit_entries_older_than_days: 60
    delete_audit_entries_older_than_days_custom:
      DIRECT_LINK_EXECUTION: 2
  oauth:
    tokens_lifetime:
      webapp: [1200]
      client_app: [3600, 5184000] # 60 days
      admin: [3600, 5184000]
      user: [3600, 5184000]
      broker: [3600, 5184000]

swiftmailer:
  encryption: "%mailer_encryption%"
  host: "%mailer_host%"
  password: "%mailer_password%"
  port: "%mailer_port%"
  spool:
    type: memory
  transport: "%mailer_transport%"
  username: "%mailer_user%"

twig:
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"
